# Generated by Django 3.0.4 on 2020-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('energy', models.FloatField(max_length=20)),
                ('reactive_energy', models.FloatField(max_length=20)),
                ('power', models.FloatField(max_length=20)),
                ('maximeter', models.FloatField(max_length=20)),
                ('reactive_power', models.FloatField(max_length=20)),
                ('voltage', models.FloatField(max_length=20)),
                ('intensity', models.FloatField(max_length=20)),
                ('power_factor', models.FloatField(max_length=20)),
            ],
        ),
    ]
